on:
  push:
    branches:
      - main 
jobs: 
    JobA:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Running tests"
        - name: Run tests
          run: |
            echo "Running tests"
            echo "Tests passed"

    JobB:  
      runs-on: ubuntu-latest
      needs: JobA 
      steps:
        - run: echo "Running tests"
        - name: Run tests
        