on:
  push:
    branches:
      - master

jobs:
  build_ppy_app:
    runs-on: ubuntu-latest
    steps:
    - name: install python
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      
  